-- EXERCICIOS AULA 3

-- EX1

ALTER TABLE ITEM_PRODUTO
    ADD TIPO_MEDIDA VARCHAR2(30);
    
-- EX2 

ALTER TABLE ITEM_PRODUTO
    ADD CONSTRAINT CK_ITEM_PRODUTO_TIPO
        CHECK (TIPO_MEDIDA IN ('LITRO', 'KILO', 'UNIDADE'));
        
-- EX3

ALTER TABLE MATERIA_PRIMA
    DROP CONSTRAINT UK_MATERIA_PRIMA;   
    
-- EX4

SELECT
    TABLE_NAME,
    CONSTRAINT_TYPE,
    CONSTRAINT_NAME,
    SEARCH_CONDITION
FROM USER_CONSTRAINTS
    WHERE TABLE_NAME IN ('CATEGORIA', 'PRODUTO',  'ITEM_PRODUTO', 'MATERIA_PRIMA')
    ORDER BY 1, 2, 3;
    
-- PARTE 2
-- EX1
-- CRIAR A SEQUENCIA

CREATE SEQUENCE SEQ_CATEGORIA;

-- EX2
-- POPULAR A TABELA COM ALGUNS REGISTROS

INSERT INTO CATEGORIA
    VALUES (10, 'DOCE');

INSERT INTO CATEGORIA
    VALUES (SEQ_CATEGORIA.NEXTVAL, 'BEBIDA');

INSERT INTO CATEGORIA
    VALUES (SEQ_CATEGORIA.NEXTVAL, 'CONGELADO');

COMMIT;

SELECT * FROM CATEGORIA;



